permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author: 
  name: Zhengquan Yang
  email: yangzhengquan@gmail.com
  link: http://zhengquan.github.io
  weibo: http://weibo.com/guru 
  github: https://github.com/Zhengquan

# 站点信息
title: Always Somewhere
description: Zhengquan's personal blog
url: http://zhengquan.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://zhengquan.github.io/assets/images/avatar.jpg
favicon: http://zhengquan.github.io/assets/images/favicon.ico

# google analytics 设置
ga:
  id: UA-73907063-1
  url: zhengquan.github.io

# disqus 设置
disqus:
  shortname: zhengquan-blog
